# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3c00569296f4bb338851cfa7be9f65db6e6396918b5eaa0109a9bdaf737f59a3065343b2490707069fd3c6586df21dd4566ab952fa3a09ba456171dca70dcb4
  MAILCHIMP_LIST_ID: ba0dfe1dc3
  MAILCHIMP_API_KEY: cfb6974c7753bc2a429ddbd518709551-us11
  STRIPE_API_KEY: sk_test_sdsqSesXYYEQayvl1ucBGfPd
  STRIPE_PUBLISH_KEY: pk_test_jMUKzHL4kwf1KFpFhTVA8QFu
test:
  secret_key_base: d53de943e87995c3ee459f31daee169e6f1bfc83f975d3b8226781908c6cb567573ad820417fea832894097652588c7c1b631829ead57f5574f6a7a128d540e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  publishable_key: pk_test_jMUKzHL4kwf1KFpFhTVA8QFu #<%= ENV["STRIPE_PUBLISH_KEY"] %>
  secret_key: sk_test_sdsqSesXYYEQayvl1ucBGfPd #<%= ENV["STRIPE_API_KEY"] %>
